### PR TITLE
Updated Pack Info & Added AOA3 Runes, Banners And Shields(See Below).

### PR DESCRIPTION
**Pull request by KrLite**
Updated Pack Info & Added AOA3 Runes, Banners And Shields(See Below).
Updated pack.png, making it feels more "broad-minded".
It was good enough, but it could be better in some ways.

Updated pack.mcmeta, making it fabulous with 7 colors.

Simple preview of pack.png:
image

### CODE REVIEW

**Comment by JieningYu** [comment]
pog

**Comment by KrLite** [comment]
What's new for AOA3:
New runes:
0c7b806f734e0aad16d585446da9269
Followed by banners and shields:
62d6024dcb1930dbc6e7552eaf0488a
09889edaad1aaa02b8f6f47646ee0c1

**Comment by JieningYu** [comment]
[hrsthrt74](https://github.com/hrsthrt74) is a Chinese so you can use Chinese directly()

**Comment by KrLite** [comment]
image

**Comment by hrsthrt74** [comment]
Thanks a lot :)

**Pull request merged**
